#!/usr/bin/perl -w
use Pg;

## this script generates an sql file which can be used to remove unwanted session
## information from an expression database.
##
## removes the following for the sessions marked for deletion.
##
## 1. All genes associated with that session
## 2. All user_annotation associated with that session
## 3. All keywords associated with that session
## 4. The session from the table sessions.

## The input taken is a list of sessions to keep in a tab delimited format which is
## just a copy of the sessions table dumped to file.

if(@ARGV != 2){
    die "useage : cleanup_sessions.pl dbname retain_file\n";
}

($dbname, $keepFile) = @ARGV;

open(IN, $keepFile) || die "couldn't open $keepFile $!\n";
while(<IN>){
    chomp;
    @temp = split /\t/, $_;
    ## 0 index
    ## 1 user_id
    ## 2 c_time
    ## 3 title
    ## 4 description
    $keepSessions{$temp[0]}{title} = $temp[3];
    $keepSessions{$temp[0]}{description} = $temp[4];
    $kept{$temp[0]} = 1;
}

## then get all sessions from the database and check them out..
$conn = Pg::connectdb("dbname=$dbname");
$query = $conn->exec("select * from sessions");
while(@temp = $query->fetchrow){
    if(@temp){
	if(!defined($keepSessions{$temp[0]})){
	    ## then we should mark this one for deletion, unless it happens 
	    ## to be session 0 which is special and which should not be removed..
	    if($temp[0]){
		$discardSessions{$temp[0]}{title} = $temp[3];
		$discardSessions{$temp[0]}{description} = $temp[4];
	    }
	}else{
	    delete($kept{$temp[0]});
	}
    }
}

@missedSessions = keys %kept;
print "Total number of sessions not in database : ", $#missedSessions + 1, "\n";
for $session(@missedSessions){
    print "$session\t$keepSessions{$session}{title}\t$keepSessions{$session}{description}\n";
}

@discardList = keys %discardSessions;
print "Total number of sessions to discard : ", $#discardList + 1, "\n";
open(OUT, ">remove_sessions.sql") || die "couldn't open remove_sessions.sql $!\n";
print OUT "/* sql code to remove unwanted sessions from an expression database
generated by cleanup_sessions.pl
*/\n";
print OUT "begin;\n";    ## don't commit yet.. 
for $session(@discardList){
    print "$session\t$discardSessions{$session}{title}\t$discardSessions{$session}{description}\n";
    ## and generate some sql, that we can use for this..
    ## delete keywords this is easy..
    print OUT "delete from session_keywords where index = $session;\n";
    ## delete all genes associated with this particular session..
    $query = $conn->exec("select distinct b.index, b.annotation from sessions a, user_annotation b where a.index=b.session_id and a.index=$session");
    while(@temp = $query->fetchrow){
	if($temp[1] !~ /\w+/){
	    print OUT "delete from user_annotation_genes where annotation_id=$temp[0];\n";
	    print OUT "delete from user_annotation where index = $temp[0];\n";
	}else{   ### if some text is associated with the comment, let's actually keep it..
	    print OUT "update user_annotation set session_id=0 where index=$temp[0];\n";
	}
    }
#    print OUT "delete from user_annotation_genes where annotation_id = (select distinct b.index from sessions a, user_annotation b where a.index=b.session_id and a.index=$session);\n";
    ## delete all user_annoation associated with the session..
    #print OUT "delete from user_annotation where session_id = $session;\n";
    ## and then delete from the session itself..
    print OUT "delete from sessions where index=$session;\n";
}
print OUT "commit;\n";
	    
